ash-project/ash_json_api

.formatter.exs
lib/ash_json_api.ex
lib/ash_json_api/api/api.ex
lib/ash_json_api/controllers/helpers.ex
lib/ash_json_api/controllers/response.ex
lib/ash_json_api/error/not_found.ex
lib/ash_json_api/test/test.ex
test/acceptance/get_test.exs
test/spec_compliance/fetching_data/fetching_relationships_test.exs
test/spec_compliance/fetching_data/fetching_resources_test.exs

For example: `fix: Multiply by appropriate coefficient`, or
`feat(Calculator): Correctly preserve history`
Any explanation or long form information in your commit message should be
in a separate paragraph, separated by a blank line from the primary message

chore: update tests/error messages/logging

---

test/acceptance/index_test.exs

test: Add acceptance test - index_test

---

lib/ash_json_api/includes/includer.ex
test/spec_compliance/fetching_data/inclusion_of_related_resources_test.exs

Following up from a similar refactor in Ash, refactoring the language for "side loading".

refactor: remove references to "side loading"

---

lib/ash_json_api/controllers/delete.ex
lib/ash_json_api/test/test.ex
test/acceptance/delete_test.exs

fix: delete status-code response

---

lib/ash_json_api/controllers/helpers.ex
test/acceptance/index_pagination_test.exs

Hi, I am testing this wonderful framework and I am having problems with pagination when using the json:api.
I think I have it solved with this PR, which includes tests, but I am not an advanced elixir user, and I didn't know Ash framework until last week either. :-)
So we will have to check it well. It is a very small change and does not break any test.
Thanks.

Fix pagination

---

documentation/topics/open-api.md

docs: Added OpenAPI customization section

---

.formatter.exs
lib/ash_json_api/resource/resource.ex
lib/ash_json_api/resource/route.ex
lib/ash_json_api/serializer.ex
test/acceptance/index_test.exs

PR linked to this discussion:
https://discord.com/channels/711271361523351632/1091730040699506750
Added minimal testing

improvement: added route default_fields with test

---

lib/ash_json_api/controllers/patch.ex

Change patch http reponse code from 201 to 200 to match jsonapi spec.

change patch http response code from 201 to 200 to match jsonapi spec

---

test/acceptance/get_test.exs

Adds currently failing tests for accessing public calculations

Add tests for field access and calculation access

---

test/acceptance/post_test.exs

chore: add failing test for nested error rendering

---

documentation/how_to/upgrade.md

docs: Add upgrade note about changing `api` -> `domain`

---

documentation/topics/upgrade.md

Fixing AshJsonApi.Router usage in documentation

---

lib/ash_json_api/includes/includer.ex
test/acceptance/nested_include_test.exs

demonstrate issue with linkage

---

lib/ash_json_api/error/error.ex
test/acceptance/post_test.exs

Add defimpl for NoSuchInput error

---

test/acceptance/post_test.exs

See context from discord [here](https://discord.com/channels/711271361523351632/1254774851428814930/1257373341573189703)

repro test for invalid_body atom issue

---

lib/ash_json_api/serializer.ex
test/acceptance/post_test.exs

https://github.com/ash-project/ash_json_api/issues/203

Avoid raising the condition converting the regex to string.

---

test/acceptance/patch_test.exs

test: tests for patch relationship actions with composite pkey

---

lib/mix/tasks/ash_json_api.install.ex

This PR uses the right argument in the moduledoc of the command.

Use correct command in moduledoc

---

documentation/topics/relationships.md

Doc: Fixed code sample for manage_relationship

---

lib/ash_json_api/json_schema/open_api.ex

fix: hide private arguments in open api

---

lib/ash_json_api/controllers/helpers.ex
lib/ash_json_api/request.ex

fix: add opts to all Ash.load calls

---

test/acceptance/post_test.exs

These support using a function for a value, which isn't being serialized correctly
The test fails with the following error:
```
1) test invalid_post create with validation that uses a function (Test.Acceptance.PostTest)
test/acceptance/post_test.exs:329
** (Plug.Conn.WrapperError) ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for &Test.Acceptance.PostTest.Author.zero/0 of type Function, Jason.Encoder protocol must always be explicitly implemented
code: |> post("/authors/with_age", %{
stacktrace:
(jason 1.4.4) lib/jason.ex:164: Jason.encode!/2
(ash_json_api 1.4.16) lib/ash_json_api/controllers/response.ex:14: AshJsonApi.Controllers.Response.render_errors/3
...
```
It's coming from here: https://github.com/ash-project/ash_json_api/blob/main/lib/ash_json_api/serializer.e …

chore: Add failing test for rendering responses for failing numericality validations

---

lib/ash_json_api/json_schema/open_api.ex
test/acceptance/open_api_test.exs

Preserve description with anyOf

---

lib/ash_json_api/json_schema/open_api.ex
test/ash_json_api/json_schema/open_api_test.exs

This PR adds descriptions to the results of `AshJsonApi.OpenApi.{filter_type/2, raw_filter_type/2}`.
It is related to [ash-project/ash_ai#6](https://github.com/ash-project/ash_ai/issues/6).

Add description in filter_type/2, raw_filter_type/2

---

lib/ash_json_api/json_schema/open_api.ex

This PR fixes https://github.com/ash-project/ash_json_api/pull/314#discussion_r2023095528.

Check `:description` also in `AshJsonApi.OpenApi.unwrap_any_of/1`

---

test/acceptance/patch_test.exs

This PR contains a test to reproduce an issue where a PATCH update to a nested embedded resource fails, but will succeed if a callback is present in the top level resource.
Not totally sure if partial patch updates to embedded resources are supported, but the behaviour should be consistent regardless of callbacks.

test: Add failing test for partial patch update for embeds

---

lib/ash_json_api/serializer.ex
test/spec_compliance/fetching_data/inclusion_of_related_resources_test.exs

fix: explicit linkage of empty relationships

---

test/spec_compliance/fetching_data/inclusion_of_nested_related_resources_test.exs

Here is the failing test showing that to-one linkage is missing in the payload.

Demonstrate missing linkage bug in nested includes

---

lib/ash_json_api/error/error.ex

I can definitely add a regression test if we feel that's necessary, but I was counting on the existing suite passing to indicate that the removal was stable.
The implementations for `Ash.Error.Forbidden.Policy` and `Ash.Error.Forbidden.ForbiddenField` were already present, so this is purely code removal.

[Fix] Remove default case for `class: :forbidden`
