ash-project/ash_json_api

.github/workflows/elixir.yml
Bump to ash 1.37.2 in build matrix to match `mix.exs`.
`ash_json_api` since v0.27.1 has failed to publish to [Hex](https://hex.pm/packages/ash_json_api) due to the build matrix failing on Ash 1.30.1. The release action is skipped because it depends on the full build matrix passing.
=> chore: fix release to Hex

documentation/tutorials/getting-started-with-json-api.md
I just set up my first Ash based JSON API and most of the information I personally needed was available somewhere, but it was split across the getting started guide, the readm, hexdocs and Discord (and in the end I was not sure where I found which information).
I tried to improve the Getting Started guide/tutorial so that it contains all the information I feel I needed to get to a point where I could fire a request against my own API.
All examples are based on the Helpdesk example from Ash's getting started guide.
=> Docs: update getting started

lib/ash_json_api/json_schema/json_schema.ex
This PR adds an helpful error message if a JSON API Route references a non-existent relationship.
Prior to this change, errors in case of a non-existent relationship have no context for identifying the root cause of the error or the incorrectly specified relationship
=> Raise error when json_api route depends on non-existent relationship

lib/ash_json_api/api/router.ex, lib/ash_json_api/controllers/schema.ex
This PR serves generated json schemas with the content type header `"application/schema+json"` as specified by the [json schema spec](https://json-schema.org/draft/2020-12/json-schema-core.html#section-14). 
This change also allows Firefox to pretty print the generated schema, making it more readable for us feeble humans. 
Additionally, this PR adds serving the schema from `/schema.json` ensuring non standard http clients at least have the hinting of the file extension.
=> improvement: Serve schema with json content-type

lib/ash_json_api/serializer.ex
Currently on error responses the library returns a **status** key which is a string, violating the specification as mentioned here: https://jsonapi.org/format/#error-objects
=> fix!: Status should be a string from json:api documentation

lib/ash_json_api/serializer.ex, lib/ash_json_api/test/test.ex, test/spec_compliance/fetching_data/fetching_resources_test.exs
when requiring the backing action to be named `:get` to be able to generate the self link, it is not imediately clear why the self link does not appear in the JSON:API response. Only after some digging and understanding that I would need to implement a specific action on all my resources for them to be able to link to themselfs, I found this piece of Code.
I would like to suggest, to better utilize the default `:read` action many resources have, or any other action the end user would like to use to back their JSON:API `get` route.
The route selection filter for the self link should then only require the HTTP method to be `:get` which is in scope of this project and not enforce restrictions on the backing action name, which in my opinion should be out of scope of this project and up to the …
=> improvement: Record self linking improvements

documentation/topics/open-api.md
The `Redoc.Plug.RedocUI` is in the `{:redoc_ui_plug, "~> 0.2.1"}` package. `forward/3` does not exist so I suppose the second parameter is the `to:` option.
=> docs: Update open-api.md

lib/ash_json_api/json_schema/json_schema.ex, test/acceptance/json_schema_test.exs, test/acceptance/open_api_test.exs
Swagger and Redoc seem both to expect a leading slash in the json `href` attribute in the `links` objects.
Swagger:
Redoc:
=> fix: Prepend slashes to relative paths

lib/ash_json_api/api/router.ex, lib/ash_json_api/controllers/open_api.ex, lib/ash_json_api/error/framework_error.ex
The `open_api_spex` package is set as an optional dependency, so when it's not present we need to not compile the OpenApi controller.  I considered having it return an error, but I think it's better to not include it in the routes at all if the package is missing and the server will return a 404.
=> fix(OpenApi): Don't cause a compilation failure when open_api_spex is not present.

lib/ash_json_api/api/router.ex, lib/ash_json_api/json_schema/json_schema.ex, lib/ash_json_api/json_schema/open_api.ex, test/acceptance/open_api_test.exs
Fixes a bug where included resources that don't have a json_api type show up in the top-level schema with a blank key.
```
{
...,
"schemas": {
"": {
"additionalProperties": false,
"description": "A \"Resource object\" representing a ", ...},
...
}
```
=> improvement: Filter for resources that have a json_api type defined

lib/ash_json_api/json_schema/json_schema.ex, lib/ash_json_api/json_schema/open_api.ex, lib/ash_json_api/resource/resource.ex, lib/ash_json_api/serializer.ex, test/acceptance/get_test.exs
`id` is currently being included in the attributes list in the schema (and is also being required), where it's otherwise being skipped during serialization: https://github.com/ash-project/ash_json_api/blob/main/lib/ash_json_api/serializer.ex#L599
The spec doesn't seem to include id in attributes, but it's definitely not required: https://jsonapi.org/format/#document-resource-objects
=> fix: Remove id from resource attributes

lib/ash_json_api/request.ex, test/spec_compliance/content_negotiation_test.exs
Allows users to skip strict checking of [media type parameters](https://jsonapi.org/format/#media-type-parameters) outside of `ext` and `profile`.
This was needed as an escape hatch to Dart's largest http client automatically adding a `charset=utf8` parameter (with no ability to remove it).
=> improvement: Add config to allow all media type params

lib/ash_json_api/json_schema/open_api.ex, test/acceptance/open_api_test.exs
This change adds attribute descriptions to generated `OpenApiSpex.Schema`s and adds a mapping for `Ash.Type.Float`.
=> Add type and descriptions

lib/ash_json_api/json_schema/open_api.ex, test/acceptance/open_api_test.exs, test/spec_compliance/content_negotiation_test.exs, test/spec_compliance/fetching_data/fetching_resources_test.exs
The `included` key that side loads associated records should now include public relationships added in the `json_api` `includes` key.
Also adds a fix for the `relationships` key where the schema was expecting a resource but was getting a `Ash.Resource.Relationships.*` struct instead.
=> enhancement: Add `included` key with resource references in OpenAPI schema

test/acceptance/post_test.exs
This adds a test that now fails due to the lack of calculations being returned after a post/create request.
I've included `default_fields` in an attempt to get this to return the field, in my main branch this is returning `#Ash.NotLoaded<:calculation>` which means that the field is being selected for serialisation, however, in this repo I can't seem to trigger the same behaviour. Instead, I'm getting no field back at all. I've tried upgrading the version of the underlying Ash framework to match my code but it doesn't seem to make a difference.
Either way, I'd distil this down to the following: _Calculated fields are not returned when post requests are completed_
This calculation works fine for a read requests by using the `preparations` macro or by using a `prepare` under the actions as …
=> Add test to show post requests don't return calculations

lib/ash_json_api/request.ex, lib/ash_json_api/test/test.ex, test/acceptance/links_test.exs
Uses phoenix_endpoint for link url generation if present in the conn.
Fixes https://github.com/ash-project/ash_json_api/issues/94
=> use phoenix endpoint if available

lib/ash_json_api/test/test.ex, test/acceptance/links_test.exs, test/spec_compliance/fetching_data/pagination/keyset_test.exs, test/spec_compliance/fetching_data/pagination/offset_test.exs
Adds a macro `assert_equal_links` that sorts and compares generated links against an expected links map
=> add macro for asserting on links

documentation/tutorials/getting-started-with-json-api.md
When I followed the tutorial, I wasn't sure how to get swagger UI working. It took me a while and some research to figure out that the UI is not exposed by default and that I need to use `open_api_spex`. I hope this small note would help future readers. 
Feel free to change the wording.
=> added a note about swagger ui & redoc integration

.formatter.exs, documentation/dsls/DSL:-AshJsonApi.Api.cheatmd, documentation/dsls/DSL:-AshJsonApi.Resource.cheatmd, lib/ash_json_api/api/api.ex, lib/ash_json_api/api/info.ex, lib/ash_json_api/resource/info.ex, lib/ash_json_api/resource/resource.ex, lib/ash_json_api/serializer.ex, test/acceptance/include_nil_values_test.exs
It's now possible to set `include_nil_values?` for `AshJsonApi.API` and `AshJsonApi.Resource`. If you don't set it for the API the default is `true` to make sure it does not break existing APIs. If you don't set it for a resource, it will use the value of its API.
=> Allow to include/exclude null values from the JSON output

lib/ash_json_api/includes/parser.ex, test/acceptance/nested_include_test.exs
:wave: Wrap the include keyword in list.
I added a test that return 400 without the extra clause in the map.
=> Fix nested includes wrapping :hammer:

documentation/tutorials/getting-started-with-ash-json-api.md
Update documentation to use ash_json_api v1.0 instead of 1.0.0-rc6, because it was released on 10 May.
=> update to ash_json_api deps version in docs.

documentation/tutorials/getting-started-with-ash-json-api.md, lib/ash_json_api/controllers/router.ex, lib/ash_json_api/open_api_spex_checker.ex
This text, "In general, we suggest", seemed out of place. Like something left over from a copy/paste, or perhaps it just needs a trailing ":".
I opted to remove it.
=> Rename module for consistency, and remove a bit of confusing text from documentation

documentation/tutorials/getting-started-with-ash-json-api.md
Add a bit of documentation to describe how the path to a Json api resource is calculated. Seems obvious in hindsight, but I struggled getting it right and logged [an issue (nr 154)](https://github.com/ash-project/ash_json_api/issues/154). This extra bit of documentation should help lost souls like myself.
=> add documentation to clarify how json path is calculated

.formatter.exs, documentation/dsls/DSL:-AshJsonApi.Domain.md, documentation/dsls/DSL:-AshJsonApi.Resource.md, lib/ash_json_api/controllers/delete.ex, lib/ash_json_api/controllers/delete_from_relationship.ex, lib/ash_json_api/controllers/get.ex, lib/ash_json_api/controllers/get_related.ex, lib/ash_json_api/controllers/get_relationship.ex, lib/ash_json_api/controllers/helpers.ex, lib/ash_json_api/controllers/index.ex, lib/ash_json_api/controllers/patch.ex, lib/ash_json_api/controllers/patch_relationship.ex, lib/ash_json_api/controllers/post.ex, lib/ash_json_api/controllers/post_to_relationship.ex, lib/ash_json_api/controllers/response.ex, lib/ash_json_api/resource/resource.ex, lib/ash_json_api/resource/route.ex, lib/ash_json_api/serializer.ex, lib/ash_json_api/test/test.ex, test/acceptance/delete_test.exs, test/acceptance/get_test.exs, test/acceptance/index_pagination_test.exs, test/acceptance/index_test.exs, test/acceptance/patch_test.exs, test/acceptance/post_test.exs
👋🏻 
Coming from Discord, [thread](https://discord.com/channels/711271361523351632/711271361523351636/1246127912793673809)
The idea here is to add a `metadata` option to each route that allows users to control the top-level meta of that route:
```elixir
routes do
index :read do
metadata fn query, results, request ->
%{"my" => "custom", "metadata" => "here"}
end
end
end
```
would result in
```json
{
"data": <...>,
"links": [<...>],
"meta": {
"my": "custom",
"metadata": "here",
<...any builtin metadata such as page metadata>
}
}
```
The main part of this PR that I'm a little unsure on is how I'm grabbing the query/changeset in `helpers.ex`. It seems like each route type has its own somewhat complex custom logic in there, and I'm not 100% sure that I've gotten the correct query/changeset in …
=> add ability to supply custom route metadata

lib/ash_json_api/controllers/helpers.ex, test/acceptance/patch_test.exs
When performing a patch/delete request, the arguments for the action that aren't present in the attributes for the resource raise an `InvalidInput` error on the read that precedes the actual update/destroy.
=> fix: Don't need to use arguments in fetch query

lib/ash_json_api/json_schema/json_schema.ex, lib/ash_json_api/json_schema/open_api.ex, test/acceptance/open_api_test.exs
Resources let you define a description, meant to be [used in generated documentation](https://hexdocs.pm/ash/dsl-ash-resource.html#resource-description), so I thought it would be cool to use it (if provided) when generating schema files!
Makes Swagger UI documentation from OpenAPI schema files approximately 1.8% more awesome.
=> feat: Use resource descriptions in generated schema files if present

lib/ash_json_api/controllers/helpers.ex, lib/ash_json_api/request.ex, test/acceptance/get_related_test.exs, test/acceptance/get_test.exs, test/acceptance/index_test.exs, test/acceptance/nested_include_test.exs, test/acceptance/patch_test.exs, test/acceptance/post_test.exs
see convo [here](https://discord.com/channels/711271361523351632/711271361523351636/1245473215623725106) for context. Essentially this provides a way to supply calculation arguments via a `field_inputs` query param.
=> feat: add support for calculation inputs via field_inputs query param

lib/ash_json_api/json_schema/json_schema.ex, lib/ash_json_api/json_schema/open_api.ex
AshJsonApi fails while generating the OpenApi schema for some resources when they don't have both create and update actions defined.
This change avoid assuming that the actions are defined and let the generation work.
Fixes #197
=> Fix: avoid failing openapi generation for non existing resource actions

lib/ash_json_api/error/schema_errors.ex, test/acceptance/patch_test.exs, test/acceptance/post_test.exs
Be compliant with the JSON:API spec
=> fix: add leading slash to JSON pointer in schema errors

documentation/topics/open-api.md, lib/ash_json_api/controllers/open_api.ex, lib/ash_json_api/controllers/router.ex, lib/ash_json_api/json_schema/open_api.ex, lib/ash_json_api/router.ex, test/acceptance/open_api_test.exs
The PR adds support for generating OpenAPI spec files with Mix tasks, instead of just in response to HTTP requests to the OpenAPI route.
Some new options are introduced that helps customizing the resulting spec:
- The OpenAPI title is now configurable with the `:open_api_title` opt.
- The OpenAPI version is now configurable with the `:open_api_version` opt.
- The OpenAPI server list was previously populated by getting the endpoint from a live `conn`. Since we want to support spec generation from the CLI and without access to an active connection, a new option `:phoenix_endpoint` is supported to statically provide a reference to the endpoint. Another option `:open_api_servers` is added if the user instead wants to specify a custom list of URLs.
```elixir
defmodule MyAppWeb.AshJsonApi do …
```
=> Support generating OpenAPI spec files with Mix tasks

lib/ash_json_api/json_schema/json_schema.ex, test/acceptance/patch_test.exs
---
I think allow_nil_input should be used in json api schema, but it wasn't.
Without this fix, I cannot make `allow_nil?: false` attributes to be optionally acceptable paramter in api.
=> fix: reject allow_nil_input fields in required_write_attributes

documentation/dsls/DSL-AshJsonApi.Domain.md, documentation/dsls/DSL-AshJsonApi.Resource.md, lib/ash_json_api/resource/resource.ex
From the docs that can be seen here https://hexdocs.pm/ash_json_api/dsl-ashjsonapi-resource.html#examples-12
=> docs: Remove erroneous " in generic action docs

lib/ash_json_api/json_schema/open_api.ex, test/acceptance/open_api_test.exs
Fixes #268.
This occured due to an unnecessary conversion from strings to atoms in the OpenApiSpex.Schema's required field.
=> Fix required attributes being marked as nullable in OpenAPI output

lib/ash_json_api/test/test.ex
Noticed that some of the code samples [here](https://hexdocs.pm/ash_json_api/AshJsonApi.Test.html) were a bit wonky, so fixed them!
=> docs: Add code blocks/syntax highlighting for examples in `AshJsonApi.Test`

lib/ash_json_api/igniter.ex, lib/mix/tasks/ash_json_api.install.ex, test/mix/tasks/ash_json_api.install_test.exs
Follow up to [make a follow up to add to the alias for phx.routes](https://github.com/ash-project/ash_json_api/pull/281#issuecomment-2620493935)
`ash_authentication_phoenix` didn't have what I was looking for but found it in the end 👀 
nifty `Igniter.Project.TaskAliases.add_alias/4` 🙌
=> On igniter install modify project aliases with expanded routes task

lib/ash_json_api/error/error.ex
https://discord.com/channels/711271361523351632/1254774851428814930/1337754359957553152
It introduces two improvements. The first one is about not logging validation error (and similar issues) as errors (@zachdaniel this might be a breaking change for some people). The second one is including source pointer in the message. This way, you will see
> [debug] invalid_attribute: InvalidAttribute /data/attributes/phone_number must be a valid E164 formatted phone number
instead of
> [debug] invalid_attribute: InvalidAttribute | must be a valid E164 formatted phone number
=> Use debug log level for errors by default

documentation/topics/authorize-with-json-api.md
This PR fixes a typo.
I also found another instance where "Graphql" is used instead of "json_api" here:
https://github.com/Undeadlol1/ash_json_api/blob/1a6446e681042483a0a0f540307a03b1b60524fe/documentation/topics/upgrade.md#errors:~:text=around%20Ash%20and-,AshGraphql,-.%20To%20implement%20custom
This is most likely a proper usage of the word and does not need to change. But I would like a confirmation please.
=> fix(docs): "graphql" used instead of "json_api"

lib/ash_json_api/json_schema/open_api.ex
Support `Ash.Type.{CiString, Decimal, Date, DurationName}`
=> Support more types in OpenApi

lib/ash_json_api/json_schema/open_api.ex, test/acceptance/open_api_test.exs
Fixes an issue where passing `:struct, constraints: [instance_of: resource]` as an argument would cause an error due to how `Ash.Type.Struct` was being used.
```
** (ArgumentError) `Ash.Type.Struct` is not a Spark DSL module.
(ash 3.5.0) Ash.Type.Struct.entities([:actions])
(spark 2.2.48) lib/spark/dsl/extension.ex:202: Spark.Dsl.Extension.get_entities/2
(ash 3.5.0) lib/ash/resource/info.ex:567: Ash.Resource.Info.primary_action/2
(ash_json_api 1.4.23) lib/ash_json_api/json_schema/open_api.ex:818: AshJsonApi.OpenApi.embedded_type_input/3
iex:8: (file)
```
=> Fix crash with embedded resource arguments in OpenAPI

lib/ash_json_api/json_schema/open_api.ex, test/ash_json_api/json_schema/open_api_test.exs
This PR resolves #316.
- Making `filter_type/2` internally delegate to `raw_filter_type/2` to reduce duplication.
- Replacing the ambiguous term `attribute_or_aggregate` with a clearer term, `field`.
=> Refactor `filter_type/2` of `OpenAPI` with `raw_filter_type/2`

lib/ash_json_api/json_schema/open_api.ex
Partially resolves #306.
Fixes missing JSON schema representation for these types in `ash_ai`
=> Support `UUIDv7`, `Time` type in `AshJsonApi.OpenApi`

lib/ash_json_api/json_schema/open_api.ex
This sends an `Authorization: Bearer $jwt` header instead of `api_key: $api_key` header, to match how `ash_authentication` expects it to be sent by default.
Closes #321
=> fix: config swagger to use bearer auth

lib/ash_json_api/json_schema/open_api.ex
Fixes a bug where `json_write_schema` was not called for certain cases (e.g., NewType).
This changes the order to match how `json_schema` is handled within `resource_attribute_type`.
=> fix: correct json_write_schema call order

documentation/topics/non-spec-query-parameters.md
Document the field_inputs parameter that allows passing values to calculations that require user input.
=> docs: add field_inputs to non-spec query parameters

documentation/topics/relationships.md
=> Docs: Enhance relationships documentation clarity and accuracy

.formatter.exs, documentation/dsls/DSL-AshJsonApi.Resource.md, lib/ash_json_api/includes/includer.ex, lib/ash_json_api/request.ex, lib/ash_json_api/resource/info.ex, lib/ash_json_api/resource/resource.ex, test/spec_compliance/fetching_data/inclusion_of_linkage_test.exs
This PR implements an `always_include_linkage` option on resources, that takes a list of relations that should have their linkage data always included in the resource's payload.
I implemented this for compatibility with ember-data in an application where I'm replacing jsonapi_resources (rails) by ash_json_api.
I'm not sure this should be merged:
1) It adds (unnecessary?) complexity.
2) It automatically triggers extra preloads, lowering the includes query param explicitness.
3) It seems this behavior is jsonapi_resources specific, not implemented in other jsonapi libs.
It could also have advantages, because clearly in the app I'm working on, it considerably reduces the number of requests. But it could also be due to poor query management by the old version of ember-data used by said app, …
=> improvement: add always_include_linkage param to resources

lib/ash_json_api/controllers/helpers.ex, lib/ash_json_api/request.ex, lib/ash_json_api/resource/resource.ex, test/acceptance/generic_action_index_test.exs
=> support index queries with generic actions

lib/ash_json_api/error/error.ex
=> fix: check for impl for all classes of errors.

lib/ash_json_api/includes/parser.ex
I can't remember why I added this line. It makes Ash crash when `includes` is an empty list and the query still provides one. Removing it allows for a better error msg.
=> fix: empty includes should not crash

lib/ash_json_api/json_schema/open_api.ex, test/acceptance/json_schema_test.exs
Removes the unnecessary warning that appears when processing recursive embedded resources in OpenAPI schema generation. The code already correctly handles recursion by using `$ref` references, so the warning is misleading and makes it seem like something is wrong when the behavior is actually expected and properly handled.
- Removed `Logger.warning` call in `lib/ash_json_api/json_schema/open_api.ex` when detecting recursive embedded types
- Updated test in `test/acceptance/json_schema_test.exs` to remove log capture and warning assertion
=> fix: remove unnecessary warning for recursive embedded types
